### ISSUE TITLE
Docs generated using `--structured-output` generated a 404 for `docco.js`

### ISSUE THREAD

**Issue by KrofDrakula** [jswartwood/docco#1]
The `<body>` tag contains a `<script>` tag pointing to `docco.js`. Perhaps moving this file to the generated root dir and setting a `<base>` in the `<head>` would resolve this?

This happens when generating documentation using the `happiness` branch.

**Comment by jswartwood** [comment]
This was a missed (post merge) fix.  I needed to add logic to the `.jst` file that would display the script inline when `--structured-output` or `--inline` was used.  A patch should already be in :)

**Comment by KrofDrakula** [comment]
Good, just making it explicit so this issue is easily findable. :)

**Comment by jswartwood** [comment]
Thank you, sir.
