### ISSUE TITLE
Filter does not seem to work

### ISSUE THREAD

**Issue by KrofDrakula** [jswartwood/docco#2]
What it says on the tin. Typing anything in the filter and focusing out or pressing enter doesn't filter the file list.

Issue exists in `happiness`.

**Comment by jswartwood** [comment]
Can you test this one (with the latest update) for me?  I believe this should be fixed now that the Javascript is included.  However, I'd like to make sure you aren't seeing another issue here.

**Comment by KrofDrakula** [comment]
Yup, on the latest `happiness`, this has been resolved.
