### ISSUE TITLE
Add a hotkey to access the filter box

### ISSUE THREAD

**Issue by KrofDrakula** [jswartwood/docco#4]
To perform a quick search, it would be awesome if you could just use the keyboard to do, say, `Alt+F` to focus the search box and then use the up/down keys (a-la Google Search) to focus a particular item in the list. Oh, and have something like `Alt+D` navigate straight to the filtered list and browse through the list like that.

**Comment by jswartwood** [comment]
I like this, but will have to think about how to do this without adding too much additional code... I would still love @jashkenas to merge these changes :)
