### ISSUE TITLE
Make `--structured-output` generate an `index.html` with a TOC

### ISSUE THREAD

**Issue by KrofDrakula** [jswartwood/docco#5]
It would be nice if the structured output contained a starting point for the docs instead of having to navigate to a specific HTML file when opening the directory.

**Comment by strathausen** [comment]
+1

**Comment by jswartwood** [comment]
I like this idea.  Thoughts on a layout?  Simplest would probably just be to take everything from the jump menu and make it the whole page.

**Comment by j-5-s** [comment]
Maybe a bit much, but what if it took the first set of comments from each file and added them to the index page as a short description along with the link to the full html documentation page?

**Comment by KrofDrakula** [comment]
That sounds pretty solid. Or take the filename and the first few lines of code to supplement missing comments. A book-style index would rock.
